repos:
  # Local Python tools
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check --diff src/ tests/
        language: python
        types: [python]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: ruff check --fix src/ tests/
        language: python
        types: [python]
        pass_filenames: false



  # Terraform tools
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        args: [--args=-check -recursive]
        files: ^infra/terraform/
      - id: terraform_tflint
        files: ^infra/terraform/
      - id: terraform_validate
        files: ^infra/terraform/