global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kafka-broker'



  # ETL application metrics
  - job_name: 'python-etl'
    static_configs:
      - targets: ['python-etl-stream:8000']
    metrics_path: /metrics

