hostPort: kafka:9101
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  # Kafka Broker metrics
  - pattern: kafka.server<type=(.+), name=(.+)><>Value
    name: kafka_server_$1_$2
    type: GAUGE

  # Kafka Producer metrics
  - pattern: kafka.producer<type=(.+), client-id=(.+)><>(.+)
    name: kafka_producer_$1_$3
    labels:
      client_id: $2
    type: GAUGE

  # Kafka Consumer metrics
  - pattern: kafka.consumer<type=(.+), client-id=(.+)><>(.+)
    name: kafka_consumer_$1_$3
    labels:
      client_id: $2
    type: GAUGE

  # Topic metrics
  - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Count
    name: kafka_server_brokertopicmetrics_$1_total
    labels:
      topic: $2
    type: COUNTER

  # Partition metrics
  - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+)><>Count
    name: kafka_server_brokertopicmetrics_$1_total
    type: COUNTER

  # Log size metrics
  - pattern: kafka.log<type=Log, name=Size, topic=(.+), partition=(.+)><>Value
    name: kafka_log_size_bytes
    labels:
      topic: $1
      partition: $2
    type: GAUGE

  # Request metrics
  - pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>(.+)
    name: kafka_network_requestmetrics_$1_$3
    labels:
      request: $2
    type: GAUGE