global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # JMX Exporter for Kafka metrics
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['jmx-exporter:5556']
    scrape_interval: 10s
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'streaming-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: /metrics

  # Node exporter (if needed for system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s